### ISSUE TITLE
app is not retina ready on os x

### ISSUE THREAD

**Issue by qCring** [qCring/QMLApplicationTemplate#1]
when setting the OS X display settings to Scaled (more space), the window resolution gets bad.

**Comment by phiskus** [comment]
issue is solved by just adding Highres Key bool "True":
BaseApp/Resources/info.plist
Information Property List : High Resolution Capable "True"

**Comment by phiskus** [comment]
let me find out how to change cmake files to get this with building

**Comment by qCring** [comment]
This issue should be fixed with the latest commit now!
